library(RColorBrewer)
display.brewer.info()
display.brewer.all()
display.brewer.pal(n=8,name='Dark2')
display.brewer.pal(n=8,name='Set2')
display.brewer.pal(n=8,name='Paired')
display.brewer.all()
display.brewer.pal(n=6,name='Blues')
display.brewer.pal(n=5,name='Oranges')
display.brewer.pal(n=6,name='Greys')
display.brewer.pal(name='Reds')
library(RColorBrewer)
data(VADeaths)
par(mfrow=c(2,3))
hist(VADeaths,breaks=10,col=brewer.pal(3,"Set3"),main="Set3 3colors")
hist(VADeaths,breaks=8,col=brewer.pal(3,"Set2"),main="Set2 3colors")
hist(VADeaths,breaks=7,col=brewer.pal(3,"Set1"),main="Set1 3colors")
hist(VADeaths,breaks=5,col=brewer.pal(3,"BuPu"),main="BuPu 3colors")
hist(VADeaths,breaks=2,col=brewer.pal(8,"Set3"),main="Set3 8colors")
hist(VADeaths,col=brewer.pal(8,"Greens"),main="Greens 8colors")
hist(VADeaths,breaks=10,col=brewer.pal(8,"Greens"),main="Greens 8colors")
library(tseries)
data(AirPassengers)
plot(AirPassengers ,xlab="Date",ylab="Passengers numbers(1000's)",main="Air Passengers numbers from 1949 to 1961")
plot(AirPassengers ,xlab="Date",ylab="Passengers numbers(1000's)",main="Air Passengers numbers from 1949 to 1955")
barplot(iris$Petal.Length)
barplot(iris$Sepal.Length,col=brewer.pal(3,"Set1"))
barplot(table(iris$Species,iris$Sepal.Length),col=brewer.pal(3,"Set 1"))
boxplot(iris$Petal.Length¬iris$Species)
data(iris)
par(mfrow=c(2,2))
boxplot(iris$Sepal.Length,col="red")
boxplot(iris$Sepal.Length¬iris$Species,col=heat.colors(3))
boxplot(iris$Sepal.Length¬iris$Species,col=topo.colors(3))
plot(x=iris$Petal.Length)
library(RColorBrewer)
plot(x=iris$Petal.Length,y=iris$Species)
plot(iris,col=brewer.pal(3,"Set1"))
library(tidyverse)
library(ggplot2)
library(hexbin)
library(RColorBrewer)
rf<-colorRampPalette(rev(brewer.pal(40,'Set3')))
hexbinplot(diamonds$price¬diamonds$carat,colramp=rf)
data(HairEyeColor)
mosaicplot(HairEyeColor)
data(mtcars)
as.matrix(mtcars)
heatmap(as.matrix(mtcars))
library(lattice)
attach(iris)
cor(iris[1:4])
library(correlogram)
correlogram(iris)



